name: parrkway

include:
  - path: templates.yml

services:

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    extends: arr_transcoding
    profiles: [arr-core, arr, jellyfin]
    volumes:
      - ${CONFIG}/jellyfin:/config
    labels:
      # traefik.http.routers.jellyfin.rule: "Host(`jellyfin.${PUBLIC_HOST}`) || Host(`parkway.${PUBLIC_HOST}`)"
      traefik.http.services.jellyfin.loadbalancer.server.port: "8096"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    extends: arr_default
    profiles: [arr-core, arr, jellyfin]
    # network_mode: bridge
    environment:
      WEBUI_PORT: 8080
    volumes:
      - ${CONFIG}/qbittorrent:/config
    ports:
      # - "${SECURE_IP:-127.0.0.1}:8081:8080" # Web UI (commented out as Traefik routes internally)
      - "6881:6881"         # Torrent peer port TCP
      - "6881:6881/udp"     # Torrent peer port UDP
    labels:
      # traefik.http.routers.qbittorrent.rule: "Host(`qbittorrent.${PUBLIC_HOST}`) || Host(`qbt.${PUBLIC_HOST}`)"
      traefik.http.services.qbittorrent.loadbalancer.server.port: "8080"
  
  profilarr:
    image: ghcr.io/dictionarry-hub/profilarr:latest
    container_name: profilarr
    extends: arr_default
    ports:
      - '6868:6868'
    volumes:
      - ./config:/config
    environment:
      # PUID: 1000
      # PGID: 1000
      ORIGIN: https://profilarr.585ux.com
    labels:
      traefik.http.services.profilarr.loadbalancer.server.port: "6868"
    #   PARSER_HOST: parser
    #   PARSER_PORT: 5000
    # depends_on:
    #   parser:
    #     condition: service_healthy

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    extends: arr_default
    profiles: [arr, trackers]
    volumes:
      - ${CONFIG}/prowlarr:/config
    labels:
      # traefik.http.routers.prowlarr.rule: "Host(`prowlarr.${PUBLIC_HOST}`)"
      traefik.http.services.prowlarr.loadbalancer.server.port: "9696"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    extends: arr_default
    profiles: [arr]
    volumes:
      - ${CONFIG}/sonarr:/config
    labels:
      # traefik.http.routers.sonarr.rule: "Host(`sonarr.${PUBLIC_HOST}`)"
      traefik.http.services.sonarr.loadbalancer.server.port: "8989"

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    extends: arr_default
    profiles: [arr]
    volumes:
      - ${CONFIG}/radarr:/config
    labels:
      # traefik.http.routers.radarr.rule: "Host(`radarr.${PUBLIC_HOST}`)"
      traefik.http.services.radarr.loadbalancer.server.port: "7878"

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    extends: arr_default
    profiles: [arr, books, trackers]
    volumes:
      - ${CONFIG}/jackett:/config
    labels:
      # traefik.http.routers.jackett.rule: "Host(`jackett.${PUBLIC_HOST}`)"
      traefik.http.services.jackett.loadbalancer.server.port: "9117"

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    extends: arr_default
    profiles: [arr]
    volumes:
      - ${CONFIG}/bazarr:/config
    labels:
      # traefik.http.routers.bazarr.rule: "Host(`bazarr.${PUBLIC_HOST}`)"
      traefik.http.services.bazarr.loadbalancer.server.port: "6767"

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    extends: arr_default
    profiles: [arr, books]
    volumes:
      - ${CONFIG}/audiobookshelf/config:/config
      - ${CONFIG}/audiobookshelf/metadata:/metadata
    labels:
      traefik.enable: "true"
      # traefik.http.routers.audiobookshelf.rule: "Host(`audiobookshelf.${PUBLIC_HOST}`) || Host(`abs.${PUBLIC_HOST}`)"
      traefik.http.services.audiobookshelf.loadbalancer.server.port: "80"

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    extends: default
    profiles: [time-out, dev]
    environment:
      LOG_LEVEL: debug
    security_opt:
      - seccomp=unconfined

  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    extends: arr_default
    profiles: [time-out]
    init: true
    environment:
      LOG_LEVEL: info
      PORT: 5055
    volumes:
      - ${CONFIG}/seerr:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    depends_on:
      - jellyfin
    labels:
      # traefik.http.routers.seerr.rule: "Host(`seerr.${PUBLIC_HOST}`) || Host(`request.${PUBLIC_HOST}`)"
      traefik.http.services.seerr.loadbalancer.server.port: "5055"

  lazylibrarian:
    image: lscr.io/linuxserver/lazylibrarian:latest
    container_name: lazylibrarian
    extends: arr_default
    profiles: [time-out]
    volumes:
      - ${CONFIG}/lazylibrarian:/config
    labels:
      # traefik.http.routers.lazylibrarian.rule: "Host(`lazylibrarian.${PUBLIC_HOST}`) || Host(`ll.${PUBLIC_HOST}`)"
      traefik.http.services.lazylibrarian.loadbalancer.server.port: "5299"
