services:

  default:
    image: placeholder
    restart: unless-stopped
    environment:
      USER_UID: ${UID:-1000}
      USER_GID: ${GID:-1000}
      TZ: America/New_York
    env_file:
      - ../.env
      - .env
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_RAW
      - NET_ADMIN
  
  arr_default:
    extends: default
    labels:
      traefik.enable: "true"
    volumes:
      - "${MOUNT}:/data"

  arr_transcoding:
    extends: arr_default
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - "987"  # render
      - "983"  # video